=== josh9383/mr-gamabhana/content/idea.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "props": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "ideasets": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "board": {
      "type": "string"
    },
    "standard": {
      "type": "number"
    },
    "subject": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "concepts": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "images": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rating": {
      "type": "object",
      "properties": {
        "relevance": {
          "type": "number"
        },
        "experience": {
          "type": "number"
        },
        "resources": {
          "type": "number"
        }
      },
      "required": [
        "relevance",
        "experience",
        "resources"
      ]
    }
  },
  "required": [
    "title",
    "props",
    "ideasets",
    "board",
    "standard",
    "subject",
    "categories",
    "concepts",
    "images",
    "rating"
  ]
}

=== josh9383/mr-gamabhana/content/ideas/m12/meta.json
{
  "title": "फरशा आणि दोरी वापरून भिंतींमधलं अंतर मोजणे",
  "props": ["पट्टी", "दोरी", "फरशी"],
  "ideasets": ["मापन"],
  "board": "महाराष्ट्र राज्य मंडळ",
  "standard": 4,
  "subject": "गणित",
  "categories": ["वर्गातील प्रयोग"],
  "concepts": ["अंतर", "लांबी", "एकक" ,"रूपांतर", "मापन"],
  "images": ["1.jpg","2.jpg"],
  "rating": {
    "relevance": 5,
    "experience": 4,
    "resources": 5
  }
}

=== josh9383/mr-gamabhana/content/ideas/m11/meta.json
{
  "title": "पट्टीने सेमी-मिमी मापन आणि काडी-दोरीची जुळणी",
  "props": ["पट्टी", "काड्या", "दोरी"],
  "ideasets": ["मापन"],
  "board": "महाराष्ट्र राज्य मंडळ",
  "standard": 4,
  "subject": "गणित",
  "categories": ["वर्गातील प्रयोग", "गट-उपक्रम"],
  "concepts": ["मापन", "तुलना"],
  "images": ["1.jpg"],
  "rating": {
    "relevance": 4,
    "experience": 5,
    "resources": 5
  }
}

=== josh9383/mr-gamabhana/content/ideas/m13/meta.json
{
  "title": "पिशवी, मीठ आणि पोहे वापरून वस्तुमान मापन आणि तुलना",
  "props": ["पिशवी", "मीठ", "पोहे","पट्टी"],
  "ideasets": ["मापन"],
  "board": "महाराष्ट्र राज्य मंडळ",
  "standard": 4,
  "subject": "गणित",
  "categories": ["वर्गातील प्रयोग"],
  "concepts": ["वस्तुमान", "मापन", "एकक", "तुलना"],
  "images": ["1.jpg"],
  "rating": {
    "relevance": 4,
    "experience": 4,
    "resources": 5
  }
}

=== josh9383/mr-gamabhana/content/ideas/m19/meta.json
{
  "title": "फुली-गोळा खेळातून क्षेत्रफळाची ओळख",
  "props": ["फळा", "खडू"],
  "ideasets": ["क्षेत्रफळ"],
  "board": "महाराष्ट्र राज्य मंडळ",
  "standard": 4,
  "subject": "गणित",
  "categories": ["वर्गातील प्रयोग"],
  "concepts": ["क्षेत्रफळ", "एकक" ,"चौरस", "मापन", "आकार"],
  "images": ["1.jpg","2.jpg"],
  "rating": {
    "relevance": 4,
    "experience": 4,
    "resources": 5
  }
}

=== josh9383/mr-gamabhana/content/ideas/m10/meta.json
{
  "title": "वीत ते सेंटीमीटर - मापनाची गरज",
  "props": ["फीत", "पट्टी"],
  "ideasets": ["मापन"],
  "board": "महाराष्ट्र राज्य मंडळ",
  "standard": 4,
  "subject": "गणित",
  "categories": ["वर्गातील प्रयोग", "गट-उपक्रम"],
  "concepts": ["लांबी", "मापन"],
  "images": ["1.jpg"],
  "rating": {
    "relevance": 4,
    "experience": 4,
    "resources": 5
  }
}

=== josh9383/mr-gamabhana/content/ideas/m17/meta.json
{
  "title": "दोरी आणि पट्टीने परिमिती मोजूया",
  "props": ["दोरी", "पट्टी", "फळा"],
  "ideasets": ["परिमिती"],
  "board": "महाराष्ट्र राज्य मंडळ",
  "standard": 4,
  "subject": "गणित",
  "categories": ["वर्गातील प्रयोग"],
  "concepts": ["परिमिती","लांबी", "आकार"],
  "images": ["1.jpg"],
  "rating": {
    "relevance": 4,
    "experience": 4,
    "resources": 5
  }
}

=== josh9383/mr-gamabhana/content/ideas/m21/meta.json
{
  "title": "दिवाळीच्या फराळातून चित्रालेखाचे प्रमाण",
  "props": ["फळा", "खडू"],
  "ideasets": ["चित्रालेख"],
  "board": "महाराष्ट्र राज्य मंडळ",
  "standard": 4,
  "subject": "गणित",
  "categories": ["वर्गातील प्रयोग"],
  "concepts": ["चित्रालेख", "प्रमाण", "संकलन" ,"वर्गीकरण"],
  "images": ["1.jpg"],
  "rating": {
    "relevance": 5,
    "experience": 5,
    "resources": 5
  }
}

=== josh9383/mr-gamabhana/content/ideas/m15/meta.json
{
  "title": "पाण्याचा ग्लास आणि बाटली वापरून आकारमानाची ओळख",
  "props": ["पाणी", "बाटली", "ग्लास"],
  "ideasets": ["मापन"],
  "board": "महाराष्ट्र राज्य मंडळ",
  "standard": 4,
  "subject": "गणित",
  "categories": ["वर्गातील प्रयोग"],
  "concepts": ["आकारमान", "मापन", "एकके","रूपांतर"],
  "images": [],
  "rating": {
    "relevance": 5,
    "experience": 4,
    "resources": 5
  }
}
